name: model_exploration
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pandas
  - numpy
  - scikit-learn
  - requests
  - nb_conda
  - scipy
  - h5py
  - matplotlib
  - pip:
    - pyod

